### ISSUE TITLE
Lucene plugin not work for local testing.

### ISSUE THREAD

**Issue by wdxxl** [sqli/sqli-cordova-lucene-plugin#2]
Hi Team:
I'm trying to use this plugin to integrate local cordova project. but the demo code not work, just throw "segments does not exist". 

I use eclipse lucene 2.9.4 to generate index folder, and just copy it to www folder. 

any suggestion?  please check my screen shot.
<img width="1258" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1063750/24345273/ea1e48e8-1301-11e7-93cd-94f4d82c78df.png">
<img width="1266" alt="screenshot" src="https://cloud.githubusercontent.com/assets/1063750/24345277/effa7d18-1301-11e7-94f8-78601ae89444.png">

**Comment by gigaga** [comment]
Hi, 

From an ios code, just indexes generated with Lucene 1 is usable. It is a limitation of the ios port. 
Try again with this release.

**Comment by wdxxl** [comment]
Hi @gigaga 
Try use Lucene 1.9.1 to generate indexes, and still not work under ios.
```
var indexPath = cordova.file.applicationDirectory+"www/storage/sdcard/full_text_index/";
```
indexPath can be founded but not result hits, also the error message still log.

**Comment by gigaga** [comment]
Your path is incorrect. There is no sdcard in ios device.

**Comment by wdxxl** [comment]
@gigaga use V1.4.3 and absolute path, it works. 
Thanks.

**Comment by gigaga** [comment]
Really good news, thanks!
